# Generated by Django 6.0.1 on 2026-01-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="manufacture",
            new_name="manufacturer",
        ),
    ]
