# Generated by Django 6.0.1 on 2026-01-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_rename_manufacture_car_manufacturer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver", "verbose_name_plural": "Drivers"},
        ),
    ]
