# Generated by Django 6.0.1 on 2026-01-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_driver_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "driver", "verbose_name_plural": "drivers"},
        ),
    ]
